# Generated by `rjournal_pdf_article()` using `knitr::purl()`: do not edit by hand
# Please edit moveEZ.Rmd to modify this file

## ----setup, include=FALSE-----------------------------------------------------
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE, 
                      out.width = "100%", fig.pos = "!")


## ----libraries----------------------------------------------------------------
library(moveEZ)
library(ggplot2)
library(dplyr)
library(biplotEZ)
library(kableExtra)
library(gapminder)


## ----comparison-table, echo=FALSE---------------------------------------------
tab <- data.frame(
  Feature = c(
    "PCA computed",
    "Variable vectors",
    "Sample coordinates",
    "Alignment",
    "Min. observations per time slice",
    "Balance across time slices",
    "Best suited for"
  ),
  `moveplot()` = c(
    "Once, on full dataset",
    "Fixed",
    "Dynamic",
    "Not required",
    "One",
    "Not required",
    "Stable variance structure; single observations per group per time"
  ),
  `moveplot2()` = c(
    "Per time slice",
    "Dynamic",
    "Dynamic",
    "Manual (align.time, reflect)",
    "Multiple",
    "Not required",
    "Evolving variance structure; manual alignment feasible"
  ),
  `moveplot3()` = c(
    "Per time slice",
    "Dynamic",
    "Dynamic",
    "Automated (GPA)",
    "Multiple",
    "Required",
    "Evolving variance structure; many time slices"
  ),
  check.names = FALSE
)


if (knitr::is_html_output()) {
  knitr::kable(tab,
      caption = "Comparison of moveplot(), moveplot2(), and moveplot3().",
      booktabs = TRUE, escape = FALSE, align = "l")
}
if (knitr::is_latex_output()) {
  knitr::kable(tab,
      caption = "Comparison of moveplot(), moveplot2(), and moveplot3().",
      booktabs = TRUE, escape = FALSE, align = "l",format = "latex") |>
  kable_styling(
    latex_options = c("hold_position", "scale_down"),
    full_width = FALSE,
    font_size = 9
  ) |>
  column_spec(1, width = "3cm") |>
  column_spec(2, width = "3.5cm") |>
  column_spec(3, width = "3.5cm") |>
  column_spec(4, width = "3.5cm")
}





## ----fixed-frame, echo = FALSE, fig.width = 6, fig.height = 4, fig.cap="The fixed variable framework where the sample coordinates in matrix ${\\bf{Z}}$ are sliced according to the levels of the time variable $T$ and the variable vectors in matrix ${\\bf{V}}$ remaining fixed."----
  knitr::include_graphics("figures/Fixed_variable_frame.png")


## ----gapminder-ex,echo=TRUE---------------------------------------------------
data("gapminder")

gapminder <- gapminder |> mutate(year = as.factor(year))

avg_year_continent <- gapminder |>
  group_by(year, continent) |>
  summarise(
    across(c(lifeExp, pop, gdpPercap), \(x) round(mean(x, na.rm = TRUE), 2)),
    .groups = "drop")


## ----bp-gap-setup, eval=FALSE, echo=TRUE--------------------------------------
# bp <- biplot(avg_year_continent, scaled = TRUE) |>
#   PCA(group.aes = avg_year_continent$continent) |>
#   samples(label.name = avg_year_continent$year) |>
#   legend.type(samples = TRUE) |>
#   plot()


## ----biplot-gap, echo = FALSE, fig.width = 6, fig.height = 4, fig.cap="PCA biplot of the gapminder data colored by continent and labeled by year."----
knitr::include_graphics("figures/biplot_gapminder.png")


## ----moveplot-html, eval = FALSE, echo = TRUE, include = knitr::is_html_output()----
# bp |> moveplot(
#     time.var = "year",
#     group.var = "continent",
#     hulls = FALSE,
#     shadow = TRUE,
#     scale.var = 3,
#     move = TRUE)
# 


## ----moveplot-latex, eval = FALSE, echo = TRUE, include = knitr::is_latex_output()----
# bp |> moveplot(
#     time.var = "year",
#     group.var = "continent",
#     hulls = FALSE,
#     scale.var = 3,
#     move = FALSE)


## ----anim-plot, echo = FALSE, fig.width = 6, fig.height = 4, fig.cap="An animation (or facet) of the PCA biplot of the gapminder data using the function moveplot() under the fixed variable framework."----
if (knitr::is_html_output()) {
  knitr::include_graphics("figures/anim1_moveplot.gif")
}
if (knitr::is_latex_output()) {
  knitr::include_graphics("figures/anim1_moveplot.png")
}


## ----climate-table, echo=FALSE------------------------------------------------
vars <- data.frame(
  Variable = c(
    "Accumulated Precipitation",
    "Daily Evaporation",
    "Temperature",
    "Soil Moisture",
    "Standardised Precipitation Index (6-month)",
    "Wind Speed"
  ),
  Abbreviation = c(
    "AP",
    "DE",
    "Temp",
    "SM",
    "SPI6",
    "Wind"
  ),
  Unit = c(
    "m/day",
    "m/day",
    "°C",
    "m³/m³",
    "Dimensionless",
    "m/s"
  ),
  Description = c(
    "Total daily precipitation accumulated over the region",
    "Net daily evaporation from the surface",
    "Mean daily surface temperature",
    "Volumetric water content of the upper soil layer",
    "Standardised index of precipitation anomaly over a 6-month window",
    "Mean daily wind speed at 10m above surface"
  )
)

if (knitr::is_html_output()) {
  knitr::kable(vars,
      caption = "Variables in the Africa climate dataset and their biplot abbreviations.",
      booktabs = TRUE, escape = FALSE, align = "l")
}
if (knitr::is_latex_output()) {
  knitr::kable(vars,
      caption = "Variables in the Africa climate dataset and their biplot abbreviations.",
      booktabs = TRUE, escape = FALSE, align = "l",format = "latex") |>
  kable_styling(
    latex_options = c("hold_position", "scale_down"),
    full_width = FALSE,
    font_size = 9
  ) |>
  column_spec(1, width = "3,5cm") |>
  column_spec(2, width = "1.5cm") |>
  column_spec(3, width = "2cm") |>
  column_spec(4, width = "6cm")
}



## ----clim-tab, echo = FALSE---------------------------------------------------
data("Africa_climate")

Africa_climate <- Africa_climate |>
  rename(
    AP       = AccPrec,
    DE       = DailyEva,
    Temp     = Temp,
    SM       = SoilMois,
    SPI6     = SPI6,
    Wind     = wind
  )

# if (knitr::is_html_output()) {
#   Africa_climate |> head(12) |>
#     kable(caption = "Africa climate dataset", escape = FALSE)
# } else {
#   Africa_climate |> head(12) |>
#     kable(caption = "Africa climate dataset", escape = FALSE,
#           format = "latex", booktabs = TRUE, linesep = "", table.pos = "!ht")
# }


## ----eval = TRUE, echo = FALSE------------------------------------------------
bp <- biplot(Africa_climate, scaled = TRUE) |> 
  PCA(group.aes = Africa_climate$Region) |> 
  samples(opacity = 0.8, col = scales::hue_pal()(10))


## ----eval = FALSE, echo = TRUE------------------------------------------------
# bp <- biplot(Africa_climate, scaled = TRUE) |>
#   PCA(group.aes = Africa_climate$Region) |>
#   samples(opacity = 0.8, col = scales::hue_pal()(10)) |>
#   plot()


## ----biplot-Afr, echo = FALSE, fig.width = 6, fig.height = 4, fig.cap="PCA biplot of the  climate data colored by region."----
knitr::include_graphics("figures/biplot_Africa_climate.png")


## ----echo=TRUE,eval=FALSE-----------------------------------------------------
# bp |> moveplot(time.var = "Year", group.var = "Region",
#                hulls = TRUE, move = FALSE)


## ----moveplot-plot, echo = FALSE, fig.width = 6, fig.height = 4, fig.cap="Faceted PCA biplots of the climate data, with each panel representing a distinct time frame, generated using moveplot()."----
knitr::include_graphics("figures/facet_Africa_climate.png")


## ----echo=TRUE,eval=FALSE,layout="l-body-outset"------------------------------
# bp |> moveplot(time.var = "Year", group.var = "Region",
#                hulls = TRUE, move = TRUE)


## ----anim2, eval=knitr::is_html_output(), echo=FALSE, fig.cap="An animation of the PCA biplot of the climate data using the function moveplot() under the fixed variable framework."----
# knitr::include_graphics("figures/anim2_moveplot.gif")


## ----dyn-frame, echo = FALSE, fig.width = 6, fig.height = 4, fig.cap="The dynamic variable framework where separate matrices ${\\bf{Z}}$ and ${\\bf{V}}$ are computed for each level of the time variable $T$."----
  knitr::include_graphics("figures/Dynamic_frame.png")


## ----eval=FALSE,echo=TRUE-----------------------------------------------------
# bp |> moveplot2(time.var = "Year", group.var = "Region",
#                hulls = TRUE, move = FALSE)


## ----moveplot-plot2, echo = FALSE, fig.width = 6, fig.height = 4, fig.cap="Faceted PCA biplots of the climate data using moveplot2()."----
  knitr::include_graphics("figures/facet2_Africa_climate.png")


## ----eval=FALSE,echo=TRUE-----------------------------------------------------
# bp |> moveplot2(time.var = "Year", group.var = "Region",
#                hulls = TRUE, move = FALSE,
#                align.time = c("1950"),
#                reflect = c("x"))


## ----climT-tab, echo = FALSE--------------------------------------------------
data("Africa_climate_target")

Africa_climate_target <- Africa_climate_target |>
  rename(
    AP       = AccPrec,
    DE       = DailyEva,
    Temp     = Temp,
    SM       = SoilMois,
    SPI6     = SPI6,
    Wind     = wind
  )

# if (knitr::is_html_output()) {
#   Africa_climate_target |> head(12) |>
#     kable(caption = "Africa climate target dataset", escape = FALSE)
# } else {
#   Africa_climate_target |> head(12) |>
#     kable(caption = "Africa climate target dataset", escape = FALSE,
#           format = "latex", booktabs = TRUE, linesep = "", table.pos = "!ht")
# }


## ----echo=TRUE----------------------------------------------------------------
viz_1989 <- Africa_climate_target |> 
  mutate("Target" = as.factor(rep("1989", nrow(Africa_climate_target))), 
         "Region" = as.factor(Region))

bp_1989 <- biplot(viz_1989, scaled = TRUE) |> 
  PCA(group.aes = viz_1989$Region)


## ----eval=FALSE, echo=TRUE----------------------------------------------------
# bp_1989 |> moveplot(time.var = "Target",
#   group.var = "Region", hulls = TRUE, move = FALSE)


## ----eval=FALSE,echo=TRUE-----------------------------------------------------
# bp |> moveplot3(time.var = "Year", group.var = "Region",
#                hulls = TRUE, move = FALSE,
#                target = Africa_climate_target)


## ----eval=FALSE,echo=TRUE-----------------------------------------------------
# bp |> moveplot3(time.var = "Year", group.var = "Region",
#                hulls = TRUE, move = FALSE,
#                target = NULL)


## ----moveplot3-facet-plot, echo = FALSE, fig.width = 6, fig.height = 4, fig.cap="Faceted PCA biplots of the climate data using `moveplot3()` where no target is specified."----
  knitr::include_graphics("figures/biplot_targetNULL.png")


## ----eval = TRUE, results = FALSE, echo = TRUE, include = FALSE---------------
results <- bp |> 
  moveplot3(time.var = "Year", group.var = "Region", hulls = TRUE, 
            move = FALSE, target = NULL) |> 
  evaluation()


## ----eval = FALSE, echo = TRUE------------------------------------------------
# results <- bp |>
#   moveplot3(time.var = "Year", group.var = "Region", hulls = TRUE,
#             move = FALSE, target = NULL) |>
#   evaluation()
# results$eval.list


## ----comp-tab, echo = FALSE---------------------------------------------------
if (knitr::is_html_output()) {
  knitr::kable(results$eval.list[1:2], 
               caption = "Measures of comparison.",
               booktabs = TRUE, escape = FALSE, format = "html")
} else {
  knitr::kable(results$eval.list[1:2], 
               caption = "Measures of comparison.",
               booktabs = TRUE, escape = FALSE, format = "latex")
}


## ----eval = FALSE,echo=TRUE---------------------------------------------------
# results$fit.plot
# results$bias.plot


## ----fit-line-plot, echo = FALSE, fig.width = 6, fig.height = 4, fig.cap="Fit measures using Procrustes Statistic (PS) and Congruence Coefficient (CC) for each time slice."----
  knitr::include_graphics("figures/fitplot.png")


## ----bias-line-plot, echo = FALSE, fig.width = 6, fig.height = 4, fig.cap="Bias measures using Absolute Mean Bias (AMB), Mean Bias (MB) and the Root Mean Squared Bias (RMSB) for each time slice."----
  knitr::include_graphics("figures/biasplot.png")

